### PR TITLE
Mc response front

### PR DESCRIPTION
**Pull request by AndrewHall797**
Add in the McResponse front end component

Also update the survey responder upon submit

Known issues, it will crash if no survey responder is selected, the form should block this from happening in a future push

closes https://github.com/AashnaNarang/SYSC4806/issues/35

image

### CODE REVIEW

**Comment by AndrewHall797** [comment]
Commit hist is ugly due to some merging with main

**Comment by AashnaNarang** [comment]
> Commit hist is ugly due to some merging with main

yeah we should fix it before merging, it has the PostgreSQL stuff in there

**Review by AashnaNarang — CHANGES_REQUESTED** [review]
LGTM but remove the changes to the files that are db related, those shouldn't be included!

**Comment by AndrewHall797** [comment]
Git hist broken here, user other branch.

**Pull request closed without merging**
